name: 'Permissions check action'
description: 'Shows you what files and permissions an action is able to access'
author: 'Andreas Røssland'
inputs:
  token:
    description: GitHub token. Defaults to `github.token`
    required: true
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
